Repository pytorch/torchdynamo, pull requests merged in 2022-10, with the labels that each got.

#1433 Minifier fixes
  test/test_minifier.py
  torchdynamo/config.py
  torchdynamo/debug_utils.py
  torchdynamo/eval_frame.py
  torchdynamo/optimizations/backends.py
  torchinductor/lowering.py
Labels: cla signed

#1440 Add support for decomp table and tracing mode in export
  test/test_export.py
  torchdynamo/eval_frame.py
Labels: cla signed

#1438 Replace type_promote with type_promotion_kind
  torchinductor/lowering.py
Labels: cla signed

#1435 Fix lowering of ceil/floor/round/trunc for int dtypes
  test/test_torchinductor_opinfo.py
  torchinductor/lowering.py
Labels: cla signed

#1444 fix argmin/max for 1-element reduction
  test/test_torchinductor_opinfo.py
  torchinductor/ir.py
Labels: cla signed

#1346 Share Aot Autograd workaround for aot_eager and inductor backend
  benchmarks/common.py
  test/test_aot_autograd.py
  test/test_torchinductor_opinfo.py
  torchdynamo/config.py
  torchdynamo/optimizations/training.py
  torchinductor/compile_fx.py
Labels: cla signed

#1449 Fix an issue that does not vectorize the most outer parallel loop
  torchinductor/codegen/cpp.py
Labels: cla signed

#1437 Revert "Convert copy.copy/deepcopy calls on tensors to pytorch ops"
  test/test_functions.py
  torchdynamo/skipfiles.py
  torchdynamo/variables/functions.py
Labels: cla signed

#1443 Fix codegen for sign
  test/test_torchinductor_opinfo.py
  torchinductor/codegen/common.py
  torchinductor/decomposition.py
Labels: cla signed

#1434 Use tf32 and add evaluation option for E2E training benchmark
  benchmarks/training_loss.py
Labels: cla signed

#1442 Type promotion for lgamma, exp, sigmoid, sqrt, cos, sin, log, silu
  test/test_torchinductor_opinfo.py
  torchinductor/lowering.py
Labels: cla signed

#1454 Set inductor logging level
  torchinductor/debug.py
Labels: cla signed

#1428 Enable all __ (dunder) ops - add intentional device-op-dtype assertion tracking in opinfo tests
  test/test_torchinductor_opinfo.py
  torchdynamo/variables/builder.py
  torchdynamo/variables/torch.py
  torchinductor/lowering.py
Labels: cla signed

#1457 added decomp for col2im
  torchinductor/decomposition.py
  torchinductor/lowering.py
Labels: cla signed

#1464 Include line numbers in debug trace
  torchdynamo/symbolic_convert.py
Labels: cla signed

#1467 Upcast kwargs for fixing a few OpInfo failures
  test/test_torchinductor.py
  test/test_torchinductor_opinfo.py
Labels: cla signed

#1468 Add buffer realize heuristic for heavy ops on CPU (only for exp now)
  torchinductor/ir.py
Labels: cla signed

#1284 Moving 0 dim CPU tensor to GPU to make unspec works well on cudagraph
  test/test_torchinductor.py
  torchinductor/compile_fx.py
  torchinductor/graph.py
Labels: cla signed

#1453 Update PyTorch pin
  Makefile
  README.md
  benchmarks/common.py
  torchinductor/decomposition.py
Labels: cla signed

#1469 Fix #1466
  test/test_repros.py
  torchdynamo/variables/lists.py
  torchdynamo/variables/tensor.py
Labels: cla signed

#1472 Update PyTorch pin
  Makefile
  README.md
Labels: cla signed

#1470 use simple codegen for where
  Makefile
  torchinductor/codegen/triton.py
  torchinductor/config.py
Labels: cla signed

#1480 Skip failed unit tests and models since moving PyTorch pin
  benchmarks/common.py
  test/test_torchinductor_opinfo.py
Labels: cla signed

#1452 Allow cpp codegen generalized for num_threads
  test/test_torchinductor.py
  torchinductor/codegen/cpp.py
  torchinductor/config.py
Labels: cla signed

#1477 Fix iinfo/finfo related opinfo failures
  test/test_torchinductor_opinfo.py
  torchinductor/decomposition.py
  torchinductor/ir.py
Labels: cla signed

#1489 Update PyTorch pin
  Makefile
  README.md
Labels: cla signed

#1481 Skip copying inputs to cuda for OpInfo cuda tests
  test/test_torchinductor.py
  test/test_torchinductor_opinfo.py
Labels: cla signed

#1487 Fix lowering for isinf and isnan for int/bool types
  test/test_torchinductor_opinfo.py
  torchinductor/lowering.py
Labels: cla signed

#1471 DDPOptimizer: register_attr_or_module -> add_submodule
  torchdynamo/optimizations/distributed.py
Labels: cla signed

#1491 User function variable supports Enum argument
  test/test_misc.py
  torchdynamo/variables/__init__.py
  torchdynamo/variables/functions.py
Labels: cla signed

#1494 Refactor torchdynamo imports to be relative
  .flake8
  Makefile
  test/mock_modules/mock_module2.py
  test/mock_modules/mock_module3.py
  torchdynamo/codegen.py
  torchdynamo/config.py
  torchdynamo/convert_frame.py
  torchdynamo/debug_utils.py
  torchdynamo/eval_frame.py
  torchdynamo/exc.py
  torchdynamo/guards.py
  torchdynamo/optimizations/backends.py
  torchdynamo/optimizations/normalize.py
  torchdynamo/optimizations/subgraph.py
  torchdynamo/optimizations/training.py
  torchdynamo/output_graph.py
  torchdynamo/symbolic_convert.py
  torchdynamo/testing.py
  torchdynamo/utils.py
  torchdynamo/variables/builder.py
  torchdynamo/variables/builtin.py
  torchdynamo/variables/dicts.py
  torchdynamo/variables/functions.py
  torchdynamo/variables/misc.py
  torchdynamo/variables/nn_module.py
  torchdynamo/variables/tensor.py
  torchdynamo/variables/torch.py
  torchinductor/triton_ops/tests/test_conv.py
  torchinductor/triton_ops/tests/test_conv1x1.py
  torchinductor/triton_ops/tests/test_conv_fusion.py
  torchinductor/triton_ops/tests/test_mm_fusion.py
Labels: cla signed

#1303 Add Adam optimizer to timm and remove extra copies in the checker
  benchmarks/timm_models.py
  torchdynamo/testing.py
Labels: cla signed

#1495 Import decomp for aten.std_mean
  test/test_torchinductor_opinfo.py
  torchinductor/decomposition.py
Labels: cla signed

#1474 add other kwarg to some loads
  torchinductor/codegen/triton.py
Labels: cla signed

#1492 Update CI for TIMM models
  .circleci/config.yml
  benchmarks/common.py
  benchmarks/timm_models.py
Labels: cla signed

#1500 Fix decomp/lowering/ExternKernel for addmm
  test/test_torchinductor_opinfo.py
  torchinductor/decomposition.py
  torchinductor/ir.py
  torchinductor/lowering.py
Labels: cla signed

#1503 Make torchinductor use relative imports
  torchdynamo/debug_utils.py
  torchdynamo/eval_frame.py
  torchdynamo/optimizations/training.py
  torchdynamo/testing.py
  torchinductor/codegen/autotuner.py
  torchinductor/codegen/triton.py
  torchinductor/codegen/triton_template.py
  torchinductor/codegen/wrapper.py
  torchinductor/compile_fx.py
  torchinductor/config.py
  torchinductor/debug.py
  torchinductor/decomposition.py
  torchinductor/dependencies.py
  torchinductor/exc.py
  torchinductor/graph.py
  torchinductor/ir.py
  torchinductor/scheduler.py
  torchinductor/triton_ops/autotune.py
  torchinductor/triton_ops/conv.py
  torchinductor/utils.py
  torchinductor/virtualized.py
Labels: cla signed

#1493 Aot Autograd - Dont fallback with new op
  test/test_aot_autograd.py
  torchdynamo/optimizations/training.py
Labels: cla signed

#1504 put index expression in parens, to work around triton bug
  test/test_torchinductor.py
  torchinductor/codegen/triton.py
Labels: cla signed

#1507 DDPOptimizer: recompile graph after replacing subgraphs
  test/test_distributed.py
  torchdynamo/optimizations/distributed.py
Labels: cla signed

#1490 Fix an accuracy issue caused by bool tensor data format
  test/test_torchinductor.py
  torchinductor/codegen/triton.py
  torchinductor/lowering.py
Labels: cla signed

#1508 Fix assert to handle negative indices in PermuteView
  test/test_torchinductor_opinfo.py
  torchinductor/ir.py
Labels: cla signed

#1506 Run reference in original dtype for opinfo tests
  test/test_torchinductor.py
  test/test_torchinductor_opinfo.py
  torchinductor/lowering.py
Labels: cla signed

#1505 Rename test files
  .github/workflows/test-inductor.yml
  test/dynamo/__init__.py
  test/dynamo/mock_modules/__init__.py
  test/dynamo/mock_modules/mock_module1.py
  test/dynamo/mock_modules/mock_module2.py
  test/dynamo/mock_modules/mock_module3.py
  test/dynamo/test_aot_autograd.py
  test/dynamo/test_aot_cudagraphs.py
  test/dynamo/test_distributed.py
  test/dynamo/test_dynamic_shapes.py
  test/dynamo/test_export.py
  test/dynamo/test_functions.py
  test/dynamo/test_global.py
  test/dynamo/test_global_declaration.py
  test/dynamo/test_minifier.py
  test/dynamo/test_misc.py
  test/dynamo/test_model_output.py
  test/dynamo/test_modules.py
  test/dynamo/test_no_fake_tensors.py
  test/dynamo/test_nops.py
  test/dynamo/test_optimizations.py
  test/dynamo/test_optimizers.py
  test/dynamo/test_python_autograd.py
  test/dynamo/test_recompile_ux.py
  test/dynamo/test_replay_record.py
  test/dynamo/test_repros.py
  test/dynamo/test_skip_non_tensor.py
  test/dynamo/test_subgraphs.py
  test/dynamo/test_unspec.py
  test/dynamo/test_verify_correctness.py
  test/inductor/__init__.py
  test/inductor/cpp/.gitignore
  test/inductor/cpp/CMakeLists.txt
  test/inductor/cpp/test.sh
  test/inductor/cpp/test_cpp_prefix.cpp
  test/inductor/opinfo_harness.py
  test/inductor/test_torchinductor.py
  test/inductor/test_torchinductor_opinfo.py
Labels: cla signed

#1509 Allow scalar tensors for logsumexp assertion
  test/inductor/test_torchinductor_opinfo.py
  torchinductor/lowering.py
Labels: cla signed

#1502 Try enabling OOM models
  benchmarks/common.py
Labels: cla signed

#1511 Skip comparing value for empty opinfo tests
  test/inductor/test_torchinductor.py
  test/inductor/test_torchinductor_opinfo.py
Labels: cla signed

#1336 [Inductor] Corner case empty graph
  test/dynamo/test_misc.py
  torchinductor/compile_fx.py
Labels: cla signed

#1519 [inductor] Only skip CPU tests when host cpp compiler not found
  test/inductor/test_torchinductor.py
Labels: cla signed

#1447 Assertion to check if fake tensors have leaked into python
  torchdynamo/variables/builder.py
  torchdynamo/variables/builtin.py
Labels: cla signed

#1514 Update PyTorch pin
  Makefile
  README.md
  test/inductor/test_torchinductor_opinfo.py
Labels: cla signed

#1242 Extending minifier for detecting accuracy issues
  torchdynamo/config.py
  torchdynamo/debug_utils.py
  torchdynamo/optimizations/training.py
  torchdynamo/testing.py
Labels: cla signed

#1513 Add support for _get_item_by_idx
  test/dynamo/test_misc.py
  torchdynamo/variables/builder.py
  torchdynamo/variables/builtin.py
  torchdynamo/variables/nn_module.py
Labels: cla signed

#1533 Catch InvalidCxxCompiler when starting tests
  test/inductor/test_torchinductor.py
Labels: cla signed

#1436 Log beginning and end of steps, update logging levels
  documentation/TROUBLESHOOTING.md
  torchdynamo/config.py
  torchdynamo/convert_frame.py
  torchdynamo/eval_frame.py
  torchdynamo/logging.py
  torchdynamo/output_graph.py
  torchdynamo/utils.py
  torchinductor/codegen/triton.py
  torchinductor/compile_fx.py
  torchinductor/debug.py
  torchinductor/graph.py
  torchinductor/utils.py
Labels: cla signed

#1537 Make stricter bool tensor checking
  torchdynamo/debug_utils.py
  torchdynamo/utils.py
Labels: cla signed

#1539 Fix triton dependency issue
  torchinductor/utils.py
Labels: cla signed

#1542 Wrap torch.profiler.* with AutogradProfilerContextWrapperVariable
  test/dynamo/test_misc.py
  torchdynamo/variables/misc.py
  torchdynamo/variables/torch.py
  torchdynamo/variables/user_defined.py
Labels: cla signed

#1540 Index_put lowering handles 0-dim tensor
  test/inductor/test_torchinductor_opinfo.py
  torchinductor/lowering.py
Labels: cla signed

#1530 [benchmarks] Skip accuracy large models and Fix GradScaler
  benchmarks/common.py
  benchmarks/runner.py
  benchmarks/torchbench.py
Labels: cla signed

#1553 Correctly handle nested ModularIndexing
  test/inductor/test_torchinductor.py
  torchinductor/sizevars.py
Labels: cla signed

#1558 1 Line rename fix
  torchdynamo/optimizations/training.py
Labels: cla signed

#1560 Re-enable skipped tests
  test/dynamo/test_aot_cudagraphs.py
Labels: cla signed

#1547 Fallback to aten.arange for float types
  test/inductor/test_torchinductor_opinfo.py
  torchinductor/lowering.py
Labels: cla signed

#1563 fix ipex UT
  test/dynamo/test_optimizations.py
  test/dynamo/test_verify_correctness.py
Labels: cla signed

#1555 Unskip passing Opinf tests
  test/inductor/test_torchinductor_opinfo.py
Labels: cla signed

#1554 Fix lowering for scatter_reduce
  test/inductor/test_torchinductor_opinfo.py
  torchinductor/lowering.py
Labels: cla signed

#1522 Get past graph breaks in tests to enable more ops
  test/dynamo/test_repros.py
  test/inductor/test_torchinductor_opinfo.py
  torchdynamo/skipfiles.py
  torchdynamo/variables/builder.py
  torchdynamo/variables/tensor.py
  torchdynamo/variables/torch.py
Labels: cla signed

#1394 torchinductor:fix conv2d channels_last issue for CPU backend
  test/inductor/test_torchinductor.py
  torchinductor/ir.py
Labels: cla signed

#1400 Fix cache contention for multiple processes
  requirements.txt
  torchinductor/codecache.py
Labels: cla signed

#1548 Logging nit
  torchdynamo/logging.py
  torchinductor/compile_fx.py
Labels: cla signed

#1501 Add smoke test
  .circleci/config.yml
  Makefile
  README.md
  tools/verify_install.py
Labels: cla signed

#1573 Unskip tests
  test/inductor/test_torchinductor_opinfo.py
Labels: cla signed

#1576 enable int32 index for index_select
  test/inductor/test_torchinductor.py
  torchinductor/lowering.py
Labels: cla signed

#1432 Rewrite `torch._shape_as_tensor` as `tensor.size`
  test/dynamo/test_misc.py
  torchdynamo/variables/torch.py
Labels: cla signed

#1528 Update debug runbook and readme
  README.md
  documentation/TROUBLESHOOTING.md
Labels: cla signed

#1570 Relax accuracy checks for small tensors and misc
  benchmarks/runner.py
  torchdynamo/debug_utils.py
  torchdynamo/testing.py
  torchdynamo/utils.py
Labels: cla signed

#1579 fix negative indexing value for select_scatter
  test/inductor/test_torchinductor_opinfo.py
  torchinductor/lowering.py
Labels: cla signed

#1532 Update PyTorch pin
  Makefile
  README.md
  test/inductor/test_torchinductor_opinfo.py
Labels: cla signed

#1586 Add optimizer to OSS models
  benchmarks/common.py
  benchmarks/huggingface.py
  benchmarks/timm_models.py
  benchmarks/torchbench.py
Labels: cla signed

#1574 Handle the case where all the inputs are scalar
  test/inductor/test_torchinductor.py
  torchinductor/lowering.py
Labels: cla signed

#1594 README: fix python example so it works with older versions
  README.md
Labels: cla signed

#1546 DDPOptimizer: accept list output as compiled submodule output
  torchdynamo/optimizations/distributed.py
Labels: cla signed

#1596 [BE] use `<stdbool.h>`
  torchdynamo/_eval_frame.c
Labels: cla signed

#1536 Benchmark script clean up
  .circleci/config.yml
  benchmarks/common.py
  benchmarks/torchbench.py
Labels: cla signed

#1601 Looks like a bug to me
  torchinductor/scheduler.py
Labels: cla signed

#1585 Move the triton pin
  Makefile
  README.md
  torchinductor/codegen/triton.py
  torchinductor/lowering.py
  torchinductor/triton_ops/autotune.py
Labels: cla signed

#1590 Check gradient with OpInfo tests
  test/inductor/test_torchinductor.py
  test/inductor/test_torchinductor_opinfo.py
Labels: cla signed

#1583 Add minifier test for failures during AOTAutograd
  test/dynamo/test_minifier.py
Labels: cla signed

#1582 Update CI skips/fails
  test/dynamo/test_distributed.py
  test/dynamo/test_misc.py
Labels: cla signed

#1207 Clean/monitor triton cache during benchmarking
  benchmarks/common.py
  torchinductor/utils.py
Labels: cla signed

#1600 Free inputs to inductor when they are no longer needed
  test/inductor/test_torchinductor.py
  torchdynamo/debug_utils.py
  torchinductor/codegen/wrapper.py
  torchinductor/compile_fx.py
  torchinductor/scheduler.py
Labels: cla signed

#1611 Remove aot_autograd_decompositions
  torchinductor/decomposition.py
Labels: cla signed

#1606 Update PyTorch pin
  Makefile
  README.md
  test/inductor/test_torchinductor_opinfo.py
Labels: cla signed

#1608 Introduce a triton version checking
  torchinductor/triton_ops/autotune.py
Labels: cla signed

#1612 fix squeeze lowering for 0d tensors
  test/inductor/test_torchinductor_opinfo.py
  torchinductor/lowering.py
Labels: cla signed

#1610 Support setitem in Dynamo input mutation detection
  test/dynamo/test_aot_autograd.py
  test/inductor/test_torchinductor_opinfo.py
  torchdynamo/debug_utils.py
  torchdynamo/optimizations/analysis.py
Labels: cla signed

#1605 Added softplus and softplus_backwards to decomps
  test/inductor/test_torchinductor_opinfo.py
  torchinductor/decomposition.py
Labels: cla signed, inductor

#1631 Use optimize_torch in TVM's meta schedule backend
  torchdynamo/optimizations/backends.py
Labels: cla signed

#1616 fix codegen of dense masks for single number indices
  test/inductor/test_torchinductor.py
  torchinductor/codegen/triton.py
Labels: cla signed

#1634 Update PyTorch pin
  Makefile
  README.md
Labels: cla signed

#1614 Promote types for `cat`
  test/inductor/test_torchinductor.py
  torchinductor/lowering.py
Labels: cla signed

#1649 Return boxed call for inductor for empty graph
  torchinductor/compile_fx.py
Labels: cla signed

#1647 Update the naming convention for module_key for easier parsing
  torchdynamo/output_graph.py
Labels: cla signed

#1581 Fix DDPOptimizer for custom layers
  test/dynamo/test_distributed.py
  torchdynamo/optimizations/distributed.py
Labels: cla signed

#1668 add support for CPU opbench
  benchmarks/microbenchmarks/operator_inp_utils.py
  benchmarks/microbenchmarks/operatorbench.py
Labels: cla signed

#1658 handle ops that are present inputs but don't exist in core anymore
  benchmarks/microbenchmarks/operator_inp_utils.py
Labels: cla signed

#1659 [inductor] type promotion in `cat`
  test/inductor/test_torchinductor.py
  torchinductor/lowering.py
Labels: cla signed

#1671 Update PyTorch pin
  Makefile
  README.md
Labels: cla signed

#1259 Small changes so torchbench.py works in fbcode
  benchmarks/torchbench.py
Labels: cla signed

#1674 Copy inputs in minifier as inductor now clears the list
  torchdynamo/debug_utils.py
Labels: cla signed

#1650 Improvements to logging each step of dynamo + inductor
  torchdynamo/eval_frame.py
  torchdynamo/logging.py
  torchdynamo/output_graph.py
  torchdynamo/symbolic_convert.py
Labels: cla signed

#1665 fix masked_fill and where type promotion
  test/inductor/test_torchinductor.py
  torchinductor/decomposition.py
  torchinductor/lowering.py
Labels: cla signed

#1672 More fixes for move to core
  copy_to_core.sh
  test/dynamo/test_aot_cudagraphs.py
  test/inductor/test_torchinductor.py
  torchdynamo/test_case.py
  torchdynamo/variables/tensor.py
Labels: cla signed

#1486 support inplace buffer reuse
  torchinductor/codegen/common.py
  torchinductor/codegen/triton.py
  torchinductor/codegen/wrapper.py
  torchinductor/graph.py
  torchinductor/scheduler.py
Labels: cla signed

#1615 Fix graphbreak, rng fixes
  test/dynamo/test_misc.py
  torchdynamo/__init__.py
  torchdynamo/allowed_functions.py
  torchdynamo/symbolic_convert.py
  torchdynamo/variables/functions.py
  torchdynamo/variables/tensor.py
  torchdynamo/variables/torch.py
Labels: cla signed

#1680 Minor fixes so benchmarks work in core
  benchmarks/common.py
  benchmarks/huggingface.py
  test/inductor/test_torchinductor.py
  test/inductor/test_torchinductor_opinfo.py
  torchdynamo/debug_utils.py
  torchdynamo/variables/tensor.py
  torchinductor/codegen/triton_mm.j2
  torchinductor/utils.py
Labels: cla signed

#1684 Add note about move to README.md
  README.md
Labels: cla signed

#1686 fix incorrect minifier command in troubleshooting guide
  documentation/TROUBLESHOOTING.md
Labels: cla signed

#1688 fix more torchdynamo -> torch._dynamo in Troubleshooting guide
  documentation/TROUBLESHOOTING.md
Labels: cla signed

#1699 Changed `torchdynamo` to `torch._dynamo` in `README.md`
  README.md
Labels: cla signed

#1700 Bug Issue Template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: cla signed

#1710 Update installation instructions
  README.md
Labels: cla signed

#1719 Revert "Update installation instructions"
  README.md
Labels: cla signed

#1720 Update readme for alpha users
  README.md
Labels: cla signed

#1735 Update readme with smoke test steps
  README.md
Labels: documentation, cla signed

#1741 Remove bug.yml checkboxes
  .github/ISSUE_TEMPLATE/bug.yml
Labels: cla signed

#1742 Separate pitch, quick start and internals in README.md
  README.md
  documentation/DeeperDive.md
  documentation/FAQ.md
  documentation/custom-backend.md
Labels: cla signed

#1769 A few tweaks to the distributed docs
  documentation/FAQ.md
Labels: cla signed

#1777 Update Install Instructions
  README.md
Labels: documentation, cla signed
